// Generated by https://quicktype.io

export interface Bancos {
    DescripcionesCodigosDeInstituciones: Instituciones[];
}

export interface Instituciones {
    CodigoInstitucion:  string;
    NombreInstitucion?: string;
}
